### ISSUE TITLE
Investigation:core/icons

### ISSUE THREAD

**Issue by advweb-grp1** [advweb-grp1/advanced-web-final-year-project#26]
Look into font awesome icon library. Does that require additions to be made for the icon folder? or is this just another package? This will have implications for the eslint. If it is just a download package to upload then alter the eslint config to exclude the icon directory.

**Comment by AymanReh** [comment]
font-awesome-free library is packaged up into 1 package, so the eslint config will need to be updated to exclude the icons directory.

**Comment by AymanReh** [comment]
Also, bootstrap icons is also packaged up into a singular package so the eslint config will need to be updated for that too

**Comment by AymanReh** [comment]
Was wondering how to exlude the icon directory in the ESlint config.
Would it be done using:
"ignorePatterns":["//name of directory/package"]

If so would the name of the directory be the name of the packages installed e.g fontawesome-svg-core. Or would the name be something else?

**Comment by AymanReh** [comment]
ignore comment that was just deleted. I understand where i went wrong

**Comment by AymanReh** [comment]
I do not believe any changes will have to be done to the icons folder since font awesome icon and bootstrap icons are both packages which can be imported.

**Comment by rwx-yxu** [comment]
Comments are not detailed enough for everyone to understand. What is it are you suggesting to add? Bootstrap icons or font awesome? Tell us how to install them. Definitively say if there will be any changes to the icons folder if we install them.

**Comment by rwx-yxu** [comment]
During meeting, clarified that the integration is through npm install which will modify the package.json. This means that no additional files will be added to the icons directory and using eslint to ignore that file specifically will have no impact on our choice of icons to use.

**Comment by rwx-yxu** [comment]
Boot strap and font awesome are **not** the same. Boot strap icons are free and open source where as font awesome has a free and paid version. We may need to credit font awesome due to this.

Lets go with bootstrap icons.

Example install of bootstrap icons.
1. install package: `npm install bootstrap-icons`
2. add this line to main.js `import 'bootstrap-icons/font/bootstrap-icons.css'`
Example code to extract an icon to add in our component.
```
<template>
  <div>
    <h1>Bootstrap Icons Example</h1>
    <bootstrap-icon :icon="sevenCircleFillIcon" />
  </div>
</template>

<script setup>
import { BootstrapIcon } from 'vue3-bootstrap-icons'
import { biSevenCircleFill } from 'bootstrap-icons/icons'

const sevenCircleFillIcon = biSevenCircleFill
</script>
```
Key thing to point out is that around knowing what to extract from `bootstrap-icons/icons` if you go to the icon docs: https://icons.getbootstrap.com/icons/7-circle-fill/
It doesn't say import using `biSevenCircleFill`. The convention seems to be that all are basically the defined classes except without the dashes and camel case. Numbers are changed to words.
`bi-7-circle-fill` -> `biSevenCircleFill` If in doubt, Google 🙌

**Comment by rwx-yxu** [comment]
Dev spec should be to add the boostrap icon dependency.
