### ISSUE TITLE
Gene info

### ISSUE THREAD

**Issue by advweb-grp1** [advweb-grp1/advanced-web-final-year-project#48]
Need to find a way to integrate the gene info api to the application

**Comment by advweb-grp1** [comment]
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=gene&id=4606&retmode=xml

**Comment by LiamSingh64** [comment]
find ID's for all genes and post here

**Comment by advweb-grp1** [comment]
Create a composable that returns an object that has
```
{
  "GeneName": "Description"
}
```

**Comment by LiamSingh64** [comment]
| Gene | ID | Endpoint |
|--------|--------|--------|
| MYBPC3mutation | 100551308 | https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=gene&id=100551308&retmode=xml |
| MYH7 | 100184395 | https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=gene&id=100184395&retmode=xml
| MYL2 | 101351770| https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=gene&id=101351770&retmode=xml
| TNNCI| NOT FOUND|
| Cell | Cell | 
| Cell | Cell |

**Comment by LiamSingh64** [comment]
## Description of Gene (very short - sentence)
```
<Entrezgene-Set>
  <Entrezgene>
    <Entrezgene_gene>
      <Gene-ref>
        <Gene-ref_desc>DESCRIPTION HERE</Gene-ref_desc>
```
## Summary of Gene (Long - paragraph)
```
<Entrezgene-Set>
  <Entrezgene>
    <Entrezgene_summary>SUMMARY PARAGRAPH HERE</Entrezgene_summary>
```

**Comment by AymanReh** [comment]
make composable with all the mutations
fetch the api and place the data inside of an array

**Comment by AymanReh** [comment]
Currently implemented a version which gets all the xml data for each ID
Need to parse the xml to only retrieve the Gene-ref_desc and Entrezgene_summary

**Comment by LiamSingh64** [comment]
- [ ] Create 'Mutations' View
- [ ] Create RADIO group with Gene options. Only 1 mutation can be selected at any point. Radio buttons will probably pass the associated GeneID (https://github.com/advweb-grp1/advanced-web-final-year-project/issues/48#issuecomment-1518771526) to the composable so an appropriate API call can be made.
- [ ] Composable that takes GeneID, makes call to API, parses for necessary information (https://github.com/advweb-grp1/advanced-web-final-year-project/issues/48#issuecomment-1518812862) and return it.
- [ ] Display the returned data about the selected gene in an easily readable format (card).

**Comment by LiamSingh64** [comment]
##Initial Approach and Issues Faced with Fetching Data
Tried creating 'gene' store that would populate itself on user login, like hcm store., so there would have been a 'bulk' API call with the gene ID's. This store would have then been used in the MutationsView. But ran into errors with the API not reliably reaching an endpoints while looping through a list of ID'S, @AymanReh couldn't find a solution for this so for now, this approach has been abandoned.

##Less-Optimal But Working Solution
Due to issues faced with the original approach we will, FOR NOW, just have an API call made for each time the user clicks the button to retrieve data. The page passes in the GeneID for the call and successfully parsing the necessary info returned (https://github.com/advweb-grp1/advanced-web-final-year-project/issues/48#issuecomment-1518812862), and displays it in a simple card. Has been manually tested but could also write some unit/e2e tests for this
